<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cym</string>
	</array>
	<key>name</key>
	<string>cytosim</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#title</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#python_section</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>([^$]*)(?=%[^%])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign.python</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.number-sign.python</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>begin</key>
			<string>^\s*(set|new|change|run|delete|import|report|export|mark|repeat|cut|call|read|end)(?!\w)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.string.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#python_section</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\w)(\d+)?\s*(hand|simul|space|fieldbase|event|fiber|bead|solid|sphere|single|double|couple|aster|fake|bundle|nucleus)(?!\w)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.python</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.hex.python</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>name</key>
					<string>support.type.python</string>
				</dict>
			</array>
		</dict>
		<key>python_section</key>
		<dict>
			<key>begin</key>
			<string>(\[\[)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\]\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>section</key>
		<dict>
			<key>name</key>
			<string>support.type.python</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#python_section</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>^\s*(\w*)\s*(\=)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.flow.python</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.whitespace.comment.leading.python</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?!\G)</string>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.python</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#python_section</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>\(</string>
									<key>end</key>
									<string>\)</string>
									<key>name</key>
									<string>punctuation.whitespace.comment.leading.python</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#python_section</string>
										</dict>
										<dict>
											<key>captures</key>
											<dict>
												<key>1</key>
												<dict>
													<key>name</key>
													<string>support.type.python</string>
												</dict>
												<key>2</key>
												<dict>
													<key>name</key>
													<string>punctuation.whitespace.comment.leading.python</string>
												</dict>
												<key>3</key>
												<dict>
													<key>name</key>
													<string>punctuation.whitespace.comment.leading.python</string>
												</dict>
											</dict>
											<key>match</key>
											<string>(\w*)\s*\=</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>title</key>
		<dict>
			<key>begin</key>
			<string>(^[^$]*)(?=%%)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.block.unicode-raw-regex.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%%</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.block.unicode-raw-regex.python</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>string.quoted.double.block.unicode-raw-regex.python</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cytosim</string>
	<key>uuid</key>
	<string>6CDA2285-2CFB-46D3-BE03-4DB65B5A3D35</string>
</dict>
</plist>
